(function() {
var m=void 0,p=!0,q=null,s=!1;
(function(){window.zaius||(window.zaius={});if(!window.zaius.loaded){!function(a,b){this[a]=b()}("domready",function(a){function b(){var a;for(g=1;a=c.shift();)a()}var c=[],d,f=document,j=f.documentElement,e=j.doScroll,g=(e?/^loaded|^c/:/^loaded|c/).test(f.readyState);f.addEventListener&&f.addEventListener("DOMContentLoaded",d=function(){f.removeEventListener("DOMContentLoaded",d,s);b()},s);e&&f.attachEvent("onreadystatechange",d=function(){/^c/.test(f.readyState)&&(f.detachEvent("onreadystatechange",d),
b())});return a=e?function(b){if(self!=top)g?b():c.push(b);else a:{try{j.doScroll("left")}catch(d){setTimeout(function(){a(b)},50);break a}b()}}:function(a){g?a():c.push(a)}});var F={trackerUrl:window.location.protocol+"//jumbe.zaius.com",visitorCookieExpiryDays:730,referrerCookieExpiryDays:60,cookieDomain:"",idSyncs:{},includeQueryString:s,includeHash:s,convertParameters:s},y=window.JSON;"object"!==typeof y&&(y={});(function(){function a(a){return 10>a?"0"+a:a}function b(a){f.lastIndex=0;return f.test(a)?
'"'+a.replace(f,function(a){var b=g[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,d){var f,g,x,B,l=j,u,n=d[a];n&&"object"===typeof n&&"function"===typeof n.toJSON&&(n=n.toJSON(a));"function"===typeof w&&(n=w.call(d,a,n));switch(typeof n){case "string":return b(n);case "number":return isFinite(n)?String(n):"null";case "boolean":case "null":return String(n);case "object":if(!n)return"null";j+=e;u=[];if("[object Array]"===Object.prototype.toString.apply(n)){B=
n.length;for(f=0;f<B;f+=1)u[f]=c(f,n)||"null";x=0===u.length?"[]":j?"[\n"+j+u.join(",\n"+j)+"\n"+l+"]":"["+u.join(",")+"]";j=l;return x}if(w&&"object"===typeof w){B=w.length;for(f=0;f<B;f+=1)"string"===typeof w[f]&&(g=w[f],(x=c(g,n))&&u.push(b(g)+(j?": ":":")+x))}else for(g in n)Object.prototype.hasOwnProperty.call(n,g)&&(x=c(g,n))&&u.push(b(g)+(j?": ":":")+x);x=0===u.length?"{}":j?"{\n"+j+u.join(",\n"+j)+"\n"+l+"}":"{"+u.join(",")+"}";j=l;return x}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=
function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":q},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var d,f,j,e,g,w;"function"!==typeof y.stringify&&(f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g={"\b":"\\b",
"\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},y.stringify=function(a,b,d){var f;e=j="";if("number"===typeof d)for(f=0;f<d;f+=1)e+=" ";else"string"===typeof d&&(e=d);if((w=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return c("",{"":a})});"function"!==typeof y.parse&&(d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,y.parse=function(a,b){function c(a,d){var f,
j,e=a[d];if(e&&"object"===typeof e)for(f in e)Object.prototype.hasOwnProperty.call(e,f)&&(j=c(e,f),m!==j?e[f]=j:delete e[f]);return b.call(a,d,e)}var f;a=String(a);d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return f=eval("("+a+")"),"function"===
typeof b?c({"":f},""):f;throw new SyntaxError("JSON.parse");})})();var g={a:q,k:q,n:s,s:p,initialize:function(a,b){this.n=s;this.k=q;this.a=e.T(F);this.d=this.VUID=window.zaius.VUID=m;l.b=0;if(!e.e(a))throw Error("Your Zaius supplied tracker ID is required");if(b!==q&&"undefined"!==typeof b)if("object"!==typeof b)console.error("Zaius ignoring config object, type is "+typeof b);else{for(var c in b)b.hasOwnProperty(c)&&!F.hasOwnProperty(c)&&console.error("Zaius ignoring unrecognized config field: "+
c);this.a=e.f(this.a,b)}this.ha();this.k=a;this.n=p;this.ia=this.fa();this.VUID=window.zaius.VUID=this.xa();this.d=this.w();this.a.hasOwnProperty("idSyncs")&&this.sa(this.a.idSyncs)},entity:function(a,b){if(b===q||b===m)b={};var c=this.F(a+"_dimension");this.r(e.h(e.f(c,b)))},event:function(a,b){if(b===q||b===m)b={};var c=this.F(a),d=l.U(),f=this.ta();this.r(e.h(e.f(d,f,c,b)))},identify:function(a){e.e(a)&&""!==e.va(a)&&g.I(a)},anonymize:function(){g.d!==m&&(g.VUID=window.zaius.VUID=g.l());g.d=m;
e.setCookie("z_customer_id","",-100,"")},r:function(a){this.n&&(l.ca(a)&&g.I(a.customer_id),this.send(a))},q:function(){var a=Array.prototype.slice.call(arguments),b,c,d=a.shift(),f=a.shift(),j;if(!d||"string"!==typeof d)return e.console.warn("[ZAIUS] Plugin name argument is missing or not a string:",d),s;if(!f)return e.console.warn("[ZAIUS] Plugin function name argument is missing"),s;c=d.split(".");b=g[c[0]]||window.zaius[c[0]];for(j=1;j<c.length;j++){if(!b)return e.console.warn("[ZAIUS] Plugin is missing:",
d),s;b=b[c[j]]}if(b){if((c=b[f])&&"function"===typeof c)return c.apply(b,a),p;e.console.warn("[ZAIUS] Plugin function argument is missing or not a function:",d,f);return s}e.console.warn("[ZAIUS] Plugin is missing:",d);return s},F:function(a){return e.compact({zaius_js_version:"2.1.4",tracker_id:this.k,event_type:a})},ta:function(){var a=this.ia&&this.s;delete this.s;return e.compact({vuid:this.VUID,customer_id:g.d,new_user:a?1:0})},xa:function(){var a=this.j(this.i("vuid")),b=a[0],c=e.c("zaiusVuid"),
d=""+(new Date).getTime(),f=this.a.visitorCookieExpiryDays,j=this.a.cookieDomain;l.b=l.b?l.b:a[1];c&&e.z(c)&&(b=c);if(!b||!e.z(b))b=e.v();e.setCookie("vuid",b+"|"+d,f,j);return b},w:function(){var a=this.j(this.i("z_customer_id")),b=a[0],c=""+(new Date).getTime(),d=this.a.visitorCookieExpiryDays,f=this.a.cookieDomain;l.b=l.b?l.b:a[1];b!==m&&e.setCookie("z_customer_id",b+"|"+c,d,f);return b},I:function(a){var b=this.j(this.i("vuid")),c=""+(new Date).getTime(),d=this.a.visitorCookieExpiryDays,f=this.a.cookieDomain;
l.b=l.b?l.b:b[1];if(!(a===m||a===q||""===a||"undefined"===a))return g.d!==m&&g.d!=a.toString()&&(g.VUID=window.zaius.VUID=g.l()),g.d=a.toString(),e.setCookie("z_customer_id",a+"|"+c,d,f),a},l:function(){var a=this.j(this.i("vuid")),b=""+(new Date).getTime(),c=this.a.visitorCookieExpiryDays,d=this.a.cookieDomain,f=e.v();l.b=l.b?l.b:a[1];e.setCookie("vuid",f+"|"+b,c,d);return f},j:function(a){var b=m,c=0;if(a)try{var d=a.split("|"),b=d[0],c=d[1]}catch(f){}return[b,c]},i:function(a){var b,c,d,f=document.cookie.split(";"),
j=[];for(b=0;b<f.length;b++)if(c=f[b].substr(0,f[b].indexOf("=")),d=f[b].substr(f[b].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,""),c==a)try{j.push(decodeURIComponent(d))}catch(h){j.push(unescape(d))}1<j.length&&(e.setCookie(a,"",-100,window.location.hostname),e.setCookie(a,"",-100,""));return 0<j.length?j[j.length-1]:m},send:function(a){a=e.C(a);(new Image(1,1)).src=encodeURI(this.a.trackerUrl+"/zaius.gif?")+a},H:function(a){(new Image(1,1)).src=encodeURI(a)},fa:function(){return!e.getCookie("vuid")},
oa:function(){var a=[];if(e.isArray(window.zaius)){for(var b=window.zaius,c=0;c<b.length;c++)if("initialize"===b[c][0]){var d=b[c];b.splice(c,1);b.unshift(d);break}for(c=0;c<b.length;c++)try{var f=b[c].shift();"initialize"===f?this.initialize.apply(this,b[c]):"onload"===f?a.push(b[c]):"entity"===f?this.entity.apply(this,b[c]):"event"===f?this.event.apply(this,b[c]):"identify"===f?this.identify.apply(this,b[c]):"anonymize"===f?this.anonymize.apply(this,b[c]):"dispatch"===f&&this.q.apply(this,b[c])}catch(j){}}return a},
ha:function(){var a=e.getCookie("zaius_js_version"),b=this.a.visitorCookieExpiryDays,c=this.a.cookieDomain;a===m&&(a=e.getCookie("jumbe_version"),e.setCookie("jumbe_version","",-100,""));(a===m||e.K(a,"0.1.8"))&&e.setCookie("vtsrc","",-100,c);if((a===m||e.K(a,"0.1.9"))&&"undefined"===this.w())e.setCookie("z_customer_id","",-100,""),this.l();e.setCookie("zaius_js_version","2.1.4",b,c)},sa:function(a){var b=Math.round((new Date).getTime()/1E3),c=this.a.visitorCookieExpiryDays,d=this.a.cookieDomain,
f=this.Z(e.getCookie("z_idsyncs"));e.t(a,function(a,c){var d=f[a];d&&b-d.lastSynced>=c.ttl?(g.H(g.p(c)),d.lastSynced=b):d===m&&(g.H(g.p(c)),f[a]={lastSynced:b})});e.setCookie("z_idsyncs",this.ra(f),c,d)},p:function(a){var b=this.VUID.replace(/-/g,""),c=RegExp(a.vuidMacro.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&"),"g");return a.url.replace(c,b)},Z:function(a){var b={};if(a){a=a.split("\n");for(var c=0;c<a.length;c++){var d=a[c].split("\t");b[d[0]]={lastSynced:parseInt(d[1],10)}}}return b},
ra:function(a){var b="";e.t(a,function(a,d){b+=a+"\t"+d.lastSynced+"\n"});return b.substring(0,b.length-1)}},l={title:function(){return document.title},ca:function(a){return"customer_id"in a},page:function(){var a=e.za();g.a.includeQueryString===p&&(a+=e.M());g.a.includeHash===p&&(a+=e.L());return a},viewport:function(){var a,b,c=window.devicePixelRatio?window.devicePixelRatio:1;if(window.innerWidth)b=(window.innerWidth*c).toFixed(),a=(window.innerHeight*c).toFixed(),b=b+"x"+a;else if(a=document.documentElement||
document.body)b=(a.clientWidth*c).toFixed(),a=(a.clientHeight*c).toFixed(),b=b+"x"+a;return b},qa:function(){var a=this.viewport(),b=window.devicePixelRatio?window.devicePixelRatio:1,b={resolution:(screen.width*b).toFixed()+"x"+(screen.height*b).toFixed(),color_depth:screen.colorDepth+"-bit"};a&&(b.viewport=a);return b},ea:function(){var a=navigator.mimeTypes;(a=(a=a?a["application/x-java-vm"]:m)&&a.enabledPlugin)||(a="unknown"!==typeof navigator.javaEnabled&&e.da(navigator.javaEnabled)&&navigator.javaEnabled());
return a},aa:function(){var a=navigator.plugins,a=a&&e.g(a["Shockwave Flash"])?a["Shockwave Flash"]:m,b=navigator.mimeTypes,b=(b=b?b["application/x-shockwave-flash"]:m)&&b.enabledPlugin,c;if(a){var d=a.description;d&&b&&(c=d.replace(/^.*\s+(\S+\s+\S+$)/,"$1"))}else if(window.ActiveXObject){try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),c=d.GetVariable("$version")}catch(f){}if(!c)try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),c="WIN 6,0,21,0",d.Aa="always",c=d.GetVariable("$version")}catch(j){}if(!c)try{d=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),c=d.GetVariable("$version")}catch(h){}c&&(c=c.split(" ")[1].split(","),c=c[0]+"."+c[1]+" r"+c[2])}return c},R:function(){var a=this.aa(),b=navigator.language||navigator.browserLanguage,c=document.characterSet||document.charset,d={java:this.ea()?1:0};a&&(d.flash=a);b&&(d.language=b.toLowerCase());c&&(d.character_set=c.toLowerCase());return d},ua:function(){var a={},b={},c=this.S();if(c)a=c;else if(document.referrer&&(c=e.ka(document.referrer),c.hostname!==
document.location.hostname)){b.referrer=c.ba;b.referral_host=c.hostname;b.referral_path=c.path;var d=H.ga(c);d?(d.original_referral&&(b=d.original_referral,delete d.original_referral),e.f(a,d)):(a.source=c.hostname,a.medium="referral")}return e.f(b,this.V(a))},V:function(a){var b=e.getCookie("vtsrc"),b=b?e.X(b):{source:"direct",medium:"none"},c="organic"===a.medium||"cpc"===a.medium,d="referral"===a.medium,f=g.a.referrerCookieExpiryDays,j;if(a.isCampaign||c)b=a,j=p;else if(d&&("none"===b.medium||
"referral"===b.medium))b=a,j=p;a=e.$(b);e.setCookie("vtsrc",a,f);a=e.h(b);this.pa||(this.pa=p,j&&(a.landing=1));return a},S:function(){var a,b=(a=e.c("campaignSource")||e.c("utm_source"))?a.replace(/\|/g,"_"):q;if(b)return e.compact({isCampaign:p,source:b,campaign:(a=e.c("campaignName")||e.c("utm_campaign"))?a.replace(/\|/g,"_"):q,medium:(a=e.c("campaignMedium")||e.c("utm_medium"))?a.replace(/\|/g,"_"):q,keywords:(a=e.c("campaignKeyword")||e.c("utm_term"))?a.replace(/\|/g,"_"):q,content:(a=e.c("campaignContent")||
e.c("utm_content"))?a.replace(/\|/g,"_"):q})},ma:function(){var a,b,c={};if(!this.la&&window.performance&&(this.la=p,a=window.performance.timing)){var d=function(a,b){return a&&b&&a>b&&864E5>a-b?a-b:s};if(b=d(a.redirectEnd,a.redirectStart))c.redirect_time=b;if(b=d(a.domainLookupEnd-a.domainLookupStart))c.domain_lookup_time=b;if(b=d(a.connectEnd,a.connectStart))c.server_connect_time=b;if(b=d(a.responseStart,a.requestStart))c.server_response_time=b;if(b=d(a.responseEnd,a.responseStart))c.page_download_time=
b;if(b=d(a.loadEventEnd,a.domLoading))c.page_load_time=b;if(b=d(a.loadEventEnd,a.navigationStart))c.total_load_time=b}return c},P:864E5,W:function(){var a={};this.b&&(a.days_since_last_visit=Math.floor(((new Date).getTime()-new Date(+this.b))/this.P));return a},Y:function(){return e.ja(g.a.convertParameters===p)},U:function(){var a=this.Y(),b=this.qa(),c=this.ua(),d=this.R(),f=this.W(),j=this.ma(),h=e.random(),h={hostname:window.location.hostname,page:this.page(),title:this.title(),u:h};return e.f(a,
b,c,d,f,j,h)}},e={C:function(a,b){var c=[],d;for(d in a)if(a.hasOwnProperty(d)){var f=b?b+"["+d+"]":d,e=a[d];"undefined"!==typeof e&&e!==q&&c.push("object"===typeof e||"array"===typeof e?this.C(e,f):encodeURIComponent(f)+"="+encodeURIComponent(e))}return c.join("&")},c:function(a){return(a=RegExp("[\\?&]"+a+"=([^&#]*)").exec(this.ya()))?decodeURIComponent(a[1])||q:q},ya:function(){return window.location.href},za:function(){return window.location.pathname},M:function(){return window.location.search},
L:function(){return window.location.hash},ja:function(a){var b=this.M().substr(1).split("&"),c=this.L().substr(1).split("&"),d=[],f={};""!=b&&(d=d.concat(b));""!=c&&(d=d.concat(c));if(d.length)for(b=0;b<d.length;b++)if(c=d[b].split("="),2===c.length){var e=decodeURIComponent(c[0]).replace(/\s+/g,"_");if(a||"zm64_id"===e||e.match(/^zaius_alias_.+/))f[e]=decodeURIComponent(c[1])}return f},getCookie:function(a){var b,c,d,f=document.cookie.split(";");for(b=0;b<f.length;b++)if(c=f[b].substr(0,f[b].indexOf("=")),
d=f[b].substr(f[b].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,""),c==a)try{return decodeURIComponent(d)}catch(e){return unescape(d)}},setCookie:function(a,b,c,d){b=encodeURIComponent(b)+"; ";var f=new Date;f.setDate(f.getDate()+c);f="expires="+f.toUTCString()+"; ";document.cookie=a+"="+b+f+"path=/; "+(d?"domain="+d+";":"")},v:function(){var a="",b,c;for(b=0;32>b;b++){c=16*Math.random()|0;if(8==b||12==b||16==b||20==b)a+="-";a+=(12==b?4:16==b?c&3|8:c).toString(16)}return a},random:function(){return Math.round(2147483647*
Math.random())},f:function(a){for(var b=Array.prototype.slice.call(arguments,1),c=0,d;d=b[c];c++)for(var f in d)if(this.isArray(d[f])){a[f]={};for(var e=0;e<d[f].length;e++)a[f][e]=d[f][e]}else a[f]=d[f];return a},Ba:function(a,b,c){for(var d=0;d<b.length;d++)a[b[d]]!==m&&(c[b[d]]=a[b[d]]);return c},T:function(a,b){if(!this.g(a))return a;var c={};b=b||"";for(var d in a)c[b+d]=a[d];return c},h:function(a){if(!this.g(a))return a;var b=this.isArray(a)?[]:{},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=this.h(a[c]));
return b},compact:function(a){if(!this.g(a))return a;for(var b in a){var c=a[b];(c===q||c===m||c!==c||"undefined"===c)&&delete a[b]}return a},$:function(a){if(!this.g(a))return a;var b=[],c;for(c in a)b.push(c+"="+a[c]);return b.join("|")},X:function(a){if(!this.e(a))return a;var b={};a=a.split(/\|/g);for(var c=0;c<a.length;c++){var d=a[c].split(/=/);b[d[0]]=d[1]}return b},e:function(a){return"[object String]"==Object.prototype.toString.call(a)},va:function(a){return!this.e(a)?a:a.replace(/^\s\s*/,
"").replace(/\s\s*$/,"")},z:function(a){return this.e(a)&&/^[\x00-\x7F]*$/.test(a)},g:function(a){return a===Object(a)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},da:function(a){return a!==m},t:function(a,b){var c=[],d=[],f;for(f in a)a.hasOwnProperty(f)&&(c.push(f),d.push(a[f]));for(f=0;f<c.length;f++)b(c[f],d[f])},Q:/^(([^:\/?#]+):)?(\/\/([^\/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?/,ka:function(a){if(this.e(a)){var b=a.match(this.Q);return{ba:a,protocol:b[2],hostname:b[4],
path:b[5],B:b[7]?decodeURIComponent(b[7]):""}}},K:function(a,b){var c=a.split("."),d=b.split("."),c=[+c[0],+c[1],+c[2]],d=[+d[0],+d[1],+d[2]];return c[0]>d[0]?s:c[0]<d[0]?p:c[1]>d[1]?s:c[1]<d[1]?p:c[2]<d[2]},console:{}},r=window.console,C=function(){},D=["log","info","warn","error"],z=0,z=0;for(;z<D.length;z++)e.console[D[z]]=r&&r[D[z]]?r[D[z]].bind(r):C;var H={O:/^(.*\.)?(daum|eniro|naver|google|googleadservices|yahoo|msn|bing|aol|lycos|ask|altavista|netscape|cnn|about|mamma|alltheweb|voila|virgilio|baidu|alice|yandex|najdi|seznam|search|wp|onetcenter|szukacz|yam|pchome|kvasir|sesam|ozu|terra|mynet|ekolay|rambler)\.[^\.]{2,3}(\.[^\.]{2})?$/,
N:{daum:["q"],eniro:["search_word"],naver:["query"],google:["q"],googleadservices:["q"],yahoo:["p"],msn:["q"],bing:["q"],aol:["query","q"],lycos:["query"],ask:["q"],altavista:["q"],netscape:["query"],cnn:["query"],about:["terms"],mamma:["query"],alltheweb:["q"],voila:["rdata"],virgilio:["qs"],baidu:["wd"],alice:["qs"],yandex:["text"],najdi:["q"],seznam:["q"],search:["q"],wp:["szukaj"],onetcenter:["qt"],szukacz:["q"],yam:["k"],pchome:["q"],kvasir:["q"],sesam:["q"],ozu:["q"],terra:["query"],mynet:["q"],
ekolay:["q"],rambler:["words"]},ga:function(a){if(!this.G){var b=a.hostname.match(this.O);if(b&&b[2]){for(var b=b[2],c=this.N[b],d,f=0;f<c.length;f++){var j=a.B.match(RegExp("[\\?&]"+c[f]+"=([^&]*)"));if(j){d=j[1];break}}var h,c="organic";if("google"==b||"googleadservices"==b)f=a.path.split("/"),"aclk"==f[f.length-1]&&(c="cpc","googleadservices"==b&&(b="google",(a=a.B.match(/[\?&]ohost=([^&]*)/))&&a[1]&&(h={referrer:a[1],referral_host:a[1],referral_path:""})));this.G=e.compact({source:b,medium:c,
keywords:d,original_referral:h})}}return this.G}};domready(function(){setTimeout(function(){var a=g.oa();window.zaius.initialize=function(a,b){g.initialize(a,b);return this};window.zaius.onload=function(a){a instanceof Function&&setTimeout(a,0)};window.zaius.entity=function(a,b){g.entity(a,b);return this};window.zaius.event=function(a,b){g.event(a,b);return this};window.zaius.identify=function(a){g.identify(a);return this};window.zaius.anonymize=function(){g.anonymize();return this};window.zaius.dispatch=
function(){g.q.apply(g,arguments);return this};window.zaius.utils={getCookie:e.getCookie,setCookie:e.setCookie};for(var b=0;b<a.length;b++)if(a[b][0]instanceof Function)a[b][0]()},0)});if(!(window.zaius.initialize instanceof Function)){zaius=window.zaius=[];zaius.A="initialize onload entity event identify anonymize dispatch".split(" ");zaius.factory=function(a){return function(){var b=Array.prototype.slice.call(arguments);b.unshift(a);zaius.push(b);return zaius}};for(r=0;r<zaius.A.length;r++)C=zaius.A[r],
zaius[C]=zaius.factory(C)}window.zaius.loaded=p;var A={m:function(){var a=document.querySelector("#zaius_subscribe");a&&(a.hidden=p)},J:function(a){function b(a){var b="";for(k in a)b+=k+": "+a[k]+"; ";return b}function c(){var a=d.style&&d.style.banner&&"left"===d.style.banner.opens,b=d.style&&d.style.circle&&d.style.circle.left;return d.style&&d.style.banner&&"right"===d.style.banner.opens||!a&&b}var d=window.zaius.webPush.config,f=document.createElement("div");f.id="zaius_subscribe";var e="30px",
h=e,g="10px",l="10px",r="#555",v="0.5";if(d.style&&d.style.bell){var t=d.style.bell;t.width&&(e=t.width);t.height&&(h=t.height);t.top&&(g=t.top);t.left&&(l=t.left);t.fill&&(r=t.fill);t.opacity&&(v=t.opacity)}f.innerHTML='<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" width="'+e+'" height="'+h+'" viewBox="0 0 612 612" style="enable-background:new 0 0 612 612;position: relative;top: '+g+";left: "+l+";fill: "+r+";opacity: "+
v+';" xml:space="preserve"><g><g><path d="M269.442,595.309c10.35,10.35,22.373,15.355,36.391,15.355c14.36,0,26.205-5.17,36.063-15.355    c9.844-10.18,15.022-22.039,15.022-36.057H254.42C254.42,573.27,259.427,585.287,269.442,595.309z" style="color: #eee;"></path><path d="M608.659,512.17c-23.911-35.25-41.882-73.072-54.083-112.854c-12.173-39.682-23.015-97.162-32.723-172.279    c-5.648-43.742-23.555-80.645-43.406-104.506c-9.865-11.867-21.112-22.601-34.055-32.053    c-25.449-18.59-46.077-27.38-70.117-34.389c-3.333-15.692-11.41-28.634-24.367-39.062c-12.757-10.271-27.38-15.692-44.076-15.692    c-16.361,0-31.048,5.342-43.734,15.692c-12.693,10.349-20.706,23.37-24.04,39.062c-24.04,7.009-44.781,15.642-70.452,34.389    c-12.721,9.295-24.046,20.022-34.054,32.053c-19.708,23.698-37.416,60.765-43.071,104.506    c-9.702,75.117-20.849,132.498-33.05,172.279C45.258,438.998,27.444,476.82,3.675,512.17C1.403,515.555,0,518.844,0,522.52    c0,3.006,0.634,5.699,2.336,8.684c3.64,6.367,9.018,9.68,16.361,9.68h574.94c7.344,0,12.686-3.34,16.36-9.68    c1.332-3.006,2.002-6.012,2.002-9.018C612,518.51,610.796,515.318,608.659,512.17z M52.089,503.822    c20.029-34.389,35.229-72.154,45.743-112.52c10.527-40.436,20.086-93.857,29.375-159.593    c8.077-57.132,34.019-93.031,66.441-114.521c23.007-15.243,42.694-23.221,65.779-28.377c8.305-1.859,13.69-9.345,13.69-17.693    v-0.669c0-17.722,15.022-32.053,32.715-32.053c18.363,0,32.722,14.36,32.722,32.053v0.669c0,8.348,5.934,15.635,14.359,17.693    c22.972,5.62,42.979,12.814,65.438,28.377c11.262,7.807,21.24,16.468,29.717,26.375c17.23,20.144,31.675,51.092,36.726,88.145    c8.967,65.779,18.697,118.859,29.381,159.259c10.685,40.4,26.041,78.131,46.078,112.854H52.089z"></path></g></g></svg>';
e={position:"fixed",bottom:"50px",right:"50px",width:"50px",height:"50px",border:"solid 1px #f9f9f9","box-shadow":"0px 1px rgba(0,0,0,0.2)","-moz-box-shadow":"0px 1px rgba(0,0,0,0.2)","-webkit-box-shadow":"0px 1px rgba(0,0,0,0.2)","-o-box-shadow":"0px 1px rgba(0,0,0,0.2)","border-radius":"26px",cursor:"pointer","z-index":"2147483647"};d.style&&d.style.circle&&(h=d.style.circle,h.position&&(e.position=h.position),h.width&&(e.width=h.width),h.height&&(e.height=h.height),h.fill&&(e.fill=h.fill),h.border&&
(e.border=h.border),h.shadow&&(e["box-shadow"]=h.shadow,e["-moz-box-shadow "]=h.shadow,e["-webkit-box-shadow"]=h.shadow,e["-o-box-shadow"]=h.shadow),h["border-radius"]&&(e["border-radius"]=h["border-radius"]),h["z-index"]&&(e["z-index"]=h["z-index"]),h.left?(e.left=h.left,delete e.right):h.right&&(e.right=h.right),h.bottom?e.bottom=h.bottom:h.top&&(e.top=h.top,delete e.bottom));f.setAttribute("style",b(e));document.body.appendChild(f);e=document.querySelector("#zaius_subscribe");e.addEventListener("click",
function(b){a(b)});f=document.createElement("div");f.id="zaius_subscribe_banner";h={width:"0",height:"0","float":"right","border-top":"10px solid transparent","border-bottom":"10px solid transparent","border-left":"10px solid #444",top:"15px",position:"relative"};d.style&&d.style.banner&&(g=d.style.banner,g.fill&&(h["border-left"]="10px solid "+g.fill),g.height&&(h.top=parseInt(g.height)/2-10+"px"));c()&&(h["border-right"]=h["border-left"],delete h["border-left"],h["float"]="left");g={background:"#444",
"border-radius":"5px","margin-right":"10px",height:"50px"};d.style&&d.style.banner&&(l=d.style.banner,l.fill&&(g.background=l.fill),l.height&&(g.height=l.height));c()&&(delete g["margin-right"],g["margin-left"]="10px");l="Click to subscribe to notifications";d.style&&(d.style.label&&d.style.label.text)&&(l=d.style.label.text);r={display:"block",padding:"16px",color:"#fff"};d.style&&d.style.label&&(v=d.style.label,v.color&&(r.color=v.color),v.padding&&(r.padding=v.padding),v["font-size"]&&(r["font-size"]=
v["font-size"]));f.innerHTML='<div style="'+b(h)+'"></div>'+('<div style="'+b(g)+'">'+('<label style="'+b(r)+'">'+l+"</label>")+"</div>");f.setAttribute("style",b(function(){var a={position:"fixed",transform:"translateY(0) scaleX(0) translateZ(0)",transition:"transform 175ms ease-in-out,opacity 175ms ease-in-out,-webkit-transform 175ms ease-in-out","transform-origin":"right center"};c()&&(a["transform-origin"]="left center");var b=document.querySelector("#zaius_subscribe"),f=parseInt(b.style.width);
parseInt(b.style.left)?a.left=parseInt(b.style.left)+f+10+"px":a.right=parseInt(b.style.right)+f+10+"px";parseInt(b.style.top)?a.top=b.style.top:a.bottom=b.style.bottom;d.style&&d.style.banner&&(b=d.style.banner,b.left?(a.left=b.left,delete a.right):b.right&&(a.right=b.right,delete a.left),b.bottom?(a.bottom=b.bottom,delete a.top):b.top&&(a.top=b.top,delete a.bottom));return a}()));document.body.appendChild(f);e.addEventListener("mouseenter",function(){document.querySelector("#zaius_subscribe_banner").style.transform=
"translateY(0px) scaleX(1) translateZ(0px)"});e.addEventListener("mouseleave",function(){document.querySelector("#zaius_subscribe_banner").style.transform="translateY(0px) scaleX(0) translateZ(0px)"})}},E={wa:function(){var a=window.zaius.webPush.config;return navigator.serviceWorker.ready.then(function(b){b.pushManager.getSubscription().then(function(b){if(b){var d=E.D(b);b.wa().then(function(){var b={action:"remove_push_token",app_id:a.websiteID};b[a.websiteID+"_chrome_push_tokens"]=d;zaius.event("push",
b)})["catch"](function(a){console.log("error unsubcribing",a)})}})["catch"](function(a){console.log("error fetching push notification subscription",a)})})},o:function(){var a=window.zaius.webPush.config;return navigator.serviceWorker.ready.then(function(b){b.pushManager.subscribe({userVisibleOnly:p}).then(function(b){var d={action:"add_push_token",app_id:a.websiteID};d[a.websiteID+"_chrome_push_tokens"]=E.D(b);zaius.event("push",d)})["catch"](function(a){"denied"!==Notification.na&&console.log("error subscribing for push notifications",
a)})})},initialize:function(){"showNotification"in ServiceWorkerRegistration.prototype&&("denied"!==Notification.na&&"PushManager"in window)&&navigator.serviceWorker.ready.then(function(a){a.pushManager.getSubscription().then(function(a){a||A.J(function(){E.o().then(A.m)})})["catch"](function(a){console.log("error fetching push notification subscription",a)})})},D:function(a){a=a.endpoint.split("/");return a[a.length-1]}},G={o:function(a){var b=window.zaius.webPush.config;return new Promise(function(c){var d=
{action:"add_push_token",app_id:b.websiteID,zaius_alias_safari_token:a.deviceToken};d[b.websiteID+"_safari_push_tokens"]=a.deviceToken;zaius.event("push",d);c()})},initialize:function(a){var b=window.zaius.webPush.config;if("default"===a.permission){var c=g.a.trackerUrl+"/safari";b.webServiceURL&&(c=b.webServiceURL);A.J(function(){window.safari.pushNotification.requestPermission(c,b.websitePushID,{tracker_id:g.k,website_id:b.websiteID},function(a){"denied"===a.permission?A.m():"granted"===a.permission&&
G.o(a).then(A.m)})})}}};window.zaius.webPush={};window.zaius.webPush.initialize=function(a){if(a)if(a.websiteID)if(window.zaius.webPush.config=a,"serviceWorker"in navigator&&"chrome"in window)navigator.serviceWorker.register("zaius-notification-service.js").then(E.initialize)["catch"](function(a){console.log("error registering zaius-notification-service.js",a)});else"safari"in window&&"pushNotification"in window.safari&&(a.websitePushID?(a=window.safari.pushNotification.permission(a.websitePushID),
G.initialize(a)):console.log("zaius.webPush.initialize: missing required field `websitePushID`"));else console.log("zaius.webPush.initialize: missing required field `websiteID`");else console.log("zaius.webPush.initialize: missing required config object parameter")}}})();
})();

zaius.initialize('Cdh9DhMh-kQJMbJA5RROdA',{trackerUrl:'https://jumbe.zaius.com/v2'});